---
output: 
  bookdown::pdf_book: 
    keep_tex: true
    number_section: true
    fig_caption: yes
    toc: true
title: "„I have spoken and saved my soul^[Respondent 9's statement on the importance of dissent.]: a qualitative analysis of Czech constitutional Judges dissenting behaviour"
author:
- Štěpán Paulík, Humboldt Universität zu Berlin, stepan.paulik.1@hu-berlin.de
- Gor Vartazaryan, Charles University, gorike2000@gmail.com
abstract: "Dissent presents an opportunity for Judges to break away from the majority opinion and express their stance. This paper contributes to existing research, based on an identification-disagreement model, we analyzed the attitudes of Judges of the Czech Constitutional Court towards dissent. A thematic analysis of semi-structured interviews with Judges (N=9) of the CCC third decade was conducted. Our results present the process of dissent making and the perception of dissent leaders in the proces. We also reveal that there are three norm-identification groups of dissenting Judges - haters, fans and strategists. The interviews revealed that four factors primarily influence Czech constitutional court judges: prior professional experience, regulation of one's own emotions and frustrations, caseload and importance of the particular case."
geometry: margin=1in
fontsize: 11pt
doublespacing: TRUE
endnote: no
indent: true
link-citations: yes
linkcolor: blue
sansitup: FALSE
header-includes:
  - \usepackage{longtable}
  - \LTcapwidth=.95\textwidth
  - \linespread{1.05}
  - \usepackage{hyperref}
bibliography: "`r rbbt::bbt_write_bib('bibliography.bib', overwrite = TRUE, library_id = rbbt::bbt_libraries()$id[rbbt::bbt_libraries()$name == 'Kvalitativní disenty'])`"
# csl: chicago-author-date.csl
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


```

# Introduction

"I don't like them [separate opinions]. (...) Because I am a routine judge and I am of the opinion that when a collegiate body makes a decision, a person X shouldn't further comment on it, just because they were of a differing view. It is undermining the authority of that court." The previous quote has been voiced by one of the Czech Constitutional Court ("CCC") judges. The view that judges are pro-claimers of law and that a court must exercise an unanimous authority has firm roots in the European legal tradition, in which legal jurisprudence has mainly concerned itself with black letter law and its doctrine and theory. It has overlooked the internal processes and motivations and external influences on judges. Without intending to delve into the long history of scholarship on the nature of law, legal interpretation and the role of judges in the whole process, legal philosopher Hans Kelsen pronounced that "the pure theory of law does not concern itself with internal mental nor with material processes." [@kelsenReineRechtslehreEinleitung1934]. While the normative stance towards dissent is not unanimous, from a descriptive perspective, it is not yet clear either why and under what circumstances do judges dissent.

Regarding the puzzle of separate opinions and disagreement on the bench in the US context, @epsteinWhyWhenJudges2011 have come up with a theoretical model of dissenting behavior and dissent aversion and they tested to what extent do US judges behave strategically when attaching separate opinions. They found that the US judges are influenced by their political and strategic consideration, such as the collegiality costs a separate opinion may bring about or the workload they currently have. In the European context, @kelemenJudicialDissentEuropean2017 offers a mainly theoretical comparative overview of the various regimes of dissenting behavior across European courts. Hanretty has made use of dissenting behavior of Spanish and Portuguese judges to conduct a point estimation of location of the "political" position of the judges [@hanrettyDissentIberiaIdeal2012] or to investigate what does a dissent reveal about the dimension across which the disagreement runs on Estonian Supreme Court [@hanrettyJudicialDisagreementNeed2015] and the British Law Lords [@hanrettyDecisionsIdealPoints2013]. Most importantly, @wittigOccurrenceSeparateOpinions2016 has put forward and empirically tested on the German Federal Constitutional Court a theoretical *disagreement-identification* model of dissenting behavior tailored at the European context that aims to overcome the shortcomings of the traditional accounts of judicial behavior stemming from the US context. 

In the Czech context, legal scholarship concerning separate opinions has until recently been sparse, empirical legal scholarship even sparser. The latter has focused mainly on analyzing the presence of implicit voting blocs (called coalitions) in the last term of the CCC. Because the votes are not known, in conducting a network analysis, the researches have relied on the information, which judge dissented in which decision. The research has revealed that the third period of CCC between 2013-2023 is rather polarized and that there are two big dissenting coalitions of judges that clash against each other [@chmelCoOvlivnujeUstavni2021; @smekalMimopravniVlivyNa2021; @vartazaryanSitOvaAnalyza2022]. In our paper, we quantitatively analyzed the dissenting behavior of judges of the CCC. We found that the dissenting behavior depends on the potential for disagreement of any given case and workload of the judges, whereas the role of the so-called norm of consensus (for explanation of norm of consensus, see [section X](#identification-disagreement)).

This paper builds on our previous research effort, which employed quantitative methods to test hypotheses generated mainly within the rational-choice theory and within the framework of the identification-disagreement model [@paulikDisagreementBenchEmpirical2024]. In this paper, we delve deeper using a qualitative approach. Our previous research tested the rational-choice theory  on the Czech Constitutional Court  („CCC“). We choose CCC for four main reasons: firstly, CCC allows judges to dissent. Attaching a separate opinion is, however, not an obligation. The vote is not public, so if a judge votes against a decision but does not exercise the dissent, there is no way for the public to know that the judge voted against the majority. That opens up room to strategize and potentially decide not to dissent despite their disagreement with the majority outcome. Thsi phenomenon has been termed as dissent aversion in the empirical legal scholarship  [@epsteinWhyWhenJudges2011; @epsteinBehaviorFederalJudges2013; @posnerWhatJudgesJustices1993]. Previous interviews with CCC judges suggest that they do indeed exercise dissent aversion [@kyselaPravnickyOlympPortrety2015; @smekalMimopravniVlivyNa2021]. Secondly, the CCC judges can dissent alone or in group with other judges. The circumstances under which judges decide for either option have not been thoroughly researched. The relevance of such research exceeds the CCC: joint dissents are also allowed at other apex courts such as the SCOTUS. Lastly, it is hard to capture certain features solely with quantitative methods. This paper also concerns the role of, for example, unwritten rules and customs, and it results into a typology of stances of judges towards a dissent rather than inference.

The paper proceeds as follows. **Doplnit strukturu**

# Context and Literature review

In this section, we situate our research in the existing literature. [First](#theory-dissent), we present an overview of theories of court dissent. [Subsequently](#primer), to give the reader sufficient context, we present back-ground information on the CCC and its Justices.

## Dissenting theory {#theory-dissent}
In a broader sense there are a couple of ways to explain judicial-decision making and, more specifically, dissenting behavior of judges. The terms employed by these theories have sometimes diverged, the content, in our view, is rather similar. @garoupaJudicialDissentCollegial2022 divide the theories of dissenting behavior into three main categories: rational-choice, principal-agent model, and explanations by legal culture theories. With the addition of the legalist perspective as well as the identity perspective, these theories can be fit into the broader framework of theories of judicial decision-making [@epsteinIntroductionStudyComparative2024].

At first, judges were perceived as deciding simply by means of law. Although the originalists of today would still subscribe to such a view, over time, the perception of judges has changed. The attitudinal accounts posited that judges are policy oriented. In other words, judges follow their political preferences defined by their ideology and partisan identity [@epsteinIntroductionStudyComparative2024; @segalSupremeCourtAttitudinal2002]. However, as of recently, judges are now perceived as allegedly strategic and rational actors. The rational-choice theory is based on a the perception of judges as a rational, self-interested utility maximizer who balances the costs and benefits of issuing a dissenting opinion [@garoupaJudicialDissentCollegial2022; @posnerHowJudgesThink2010]. Finally, we can find different approaches focusing on various structural rather than individual features. Explanation based legal culture focuses on comparative studies and the historical development in the area. Moreover, principal-agent is a model where judges are agents and another actor, typically politicians such as the MPs, are the principals. In this setting dissents allow agents and principles to align their interests in a context of asymmetric [@garoupaJudicialDissentCollegial2022].

As with our previous study, we situate our research within the framework of the rational choice theory. Therefore, a dissenting opinion comes at costs (trade offs) and comes with potential benefits that the judges strategically weigh against each other. In general, "a potential dissenter balances the costs and benefits of issuing a dissenting opinion." [@garoupaJudicialDissentCollegial2022; @garoupaDisagreeingPrivateDissenting2022]. @epsteinWhyWhenJudges2011 presented an empirical study on dissenting behavior on the Supreme Court of the USA (“SCOTUS”) based on the strategic-economic framework of self-interested strategically motivated judges. They posit that judges have “leisure preferences, or, equivalently, effort aversion, which they trade off against their desire to have a good reputation and to express their legal and policy beliefs and preferences (and by doing so perhaps influence law and policy) by their vote, and by the judicial opinion explaining their vote, in the cases they hear.” Therefore, a dissenting opinion comes at costs (trade offs) and comes with potential benefits that the judges strategically weigh against each other. Each judge then draws different utilities from their decision to dissent and not to dissent and, therefore, the judges’ behavior exhibits between variance. They found that dissents are negatively related to the effort costs in the form of a higher workload, to collegiality costs measured by the circuit size in the court of appeals, and positively related to ideological diversity among judges in the circuit and [@epsteinWhyWhenJudges2011]

The utility of a dissenting opinion are the potential to undermine the majority opinion when the dissent is influential and the enhanced reputation that the judge enjoys. The dissenting opinion may be cited in the future by other judges or publicly analysed by legal scholars. @epsteinWhyWhenJudges2011 also argue that the judges strategically take into account collegiality costs. The collegiality costs are lower at courts that sit in larger panels, whereas they are bigger at courts that decide in smaller panels as the judges have to spent time in a smaller circle of their colleagues. Moreover, they predict that the judges may reap benefits of averting a dissent whenever they face a high workload. In that, they free up their hand to take care of more pressing work. @epsteinWhyWhenJudges2011 then empirically verify to what extent does their theory hold. They find that the US judges indeed take into account the reputation utility, the collegiality costs as well as their workload.

In the European context, @wittigOccurrenceSeparateOpinions2016 in her dissertation thesis on separate opinions at the Federal Constitutional Court of Germany ("GFCC") summarizes the potential motivations for judges to attach a separate opinion and, thus, to acquire additional costs: (1) potential of impacting future caselaw, (2) moral obligation to distance oneself from a decision that contradicts her values, (3) to convey certain image about oneself. These motivations also largely rely on the self-perceived stance towards separate opinions in general. The proponents of separate opinions view dissenting positively based on the separate opinions  being able to enrich the legal debate, being a sign of judicial independence, increasing the legitimacy of any given decision for it makes the decision more accurate of the real discussion behind it. The opponents of separate opinions mainly argue that showing the inability to speak in one voice undermines a court's legitimacy or the reputation of the dissenting judge. Such a view is perfectly in line with the quote from the introduction. Moreover, judges seeking the appreciation from the general public or legal community may act in their personal interests instead of in the court's interests. Lastly, separate opinions come at collegiality costs and may harm the mutual relationships of judges. In our study, we pose the research question RQ1: What utilities do motivate the CCC justices to dissent or not to dissent?

In her theory of dissenting behavior, Wittig makes a sharp cut from the accounts coming mainly from the US, more specifically from the research on SCOTUS, and comes up with a model of separate opinions better suited for the civil law context of the CCC, the identification-disagreement model. Wittig argues that the traditional all have limited explanatory power as such and also do not fit within the civil law context, as judges therein are deciding in a different context, bound by different procedural rules, and, thus, given differing, sometimes broader, sometimes more limited, avenues to give way to their policy preferences or strategic considerations. We now discuss the identification-disagreement model in more detail.

## Identification-disagreement model {#identification-disagreement}

Wittig introduces a non-formal model of separate opinions, the identification-disagreement model. Wittig amalgamates all the previously introduced potential motivations of judges for writing separate opinions into one cohesive and comprehensive model. The model is made up of two dimensions. The first dimension of the model covers the disagreement level. The second dimension concerns the judges’ stance and degree of self-identification of their role as a judge, Wittig terms this as a norm of consensus. Separate opinions are then “a function of a judge’s identification with the norm of consensus and the level of disagreement of judges (Wittig, 2016, pp. 74–75). Because we base our theory on the identification-disagreement model,  we now delve into the two dimensions deeper. We start with the identification with the norm of consensus and then we move on to the disagreement.


### Norm identification. 
@calderiaTimeConsensualNorms1998, p. 876-877 define a norm as "a long-run equilibrium outcome, which underpins the interaction between individuals and reflects common understandings as to what is acceptable behavior in given circumstances." The norm of consensus in turn defines the level of dissent that is acceptable at any given court [@narayanConsensualNormHigh2005; @wittigOccurrenceSeparateOpinions2016, p. 75.]. Wittig's argument is two-fold. First, in civil law traditions unlike its US counterpart, the prevailing notion of the norm of consensus is that a court should not display disagreement. Second, the extent of adherence to the norm varies among judges,^[We conducted interviews with the judges of the third term of the CCC. Practically all of them more or less directly confirmed that they share the view that judges should not display dissent at a civil law court to a very varying degree.] depending on how they weight the costs and benefits they receive from following it [@wittigOccurrenceSeparateOpinions2016, p. 75.].

A dissonance between a proposed outcome for a case and any given judge's preferences are eventually bound to happen. In such a case, the judge can either express their sincere preferences by writing a separate opinion or they can adapt their behavior according to the norm of consensus and suppress the expression of her preferences. The second route has also been termed *dissent aversion* and theoretically fleshed out by @epsteinWhyWhenJudges2011. The decision of judge faced with such a conflict whether to attach a separate opinion or whether to avert their dissent is then a function of multiple potential utilities.

Wittig draws up three types of utility that dictate various levels of the adherence to the norm of consensus. Firstly, the intrinsic utility is maximized whenever a judge behaves in accordance with their true values and opinions, setting aside their strategic or political considerations. Secondly, expressive utility is harnessed when one displays individuality and counters the notion of conformism. Thirdly, the reputational utility arises when one adjusts their publicly displayed preferences to the expectations of others. Wittig argues that maximizing the former two forms of utilities in a situation of disagreement leads to separate opinions, whereas maximizing the reputational utility in such a situation gives way to the norm of consensus, as the judge would otherwise jeopardize the court's legitimacy as well as their reputation for not adhering to commonly accepted norms [@wittigOccurrenceSeparateOpinions2016, p. 76]. We pose the second research question RQ2: how do the CCC justices understand and identify with the norm of consensus at the CCC?

### Disagreement on a bench. 

A disagreement on a bench arises when the opinions on the matter diverge during a discussion and a judge has a reason to object the majority view. For example, case characteristics play an important role. Cases with more value-laden or controversial topics may give raise to more disagreement, similarly highly complex cases leave more space for disagreement. The sources of disagreement are seemingly manifold. To elucidate them theoretically, we rely on the literature on case-space model.

The case-space model is a theoretical model developed in an attempt to model the idiosyncrasies of court decision-making, i.e. that a court is a body resolving disputes, cases [@landaDisagreementsCollegialCourts2007; @laxNewJudicialPolitics2011]. It differs from political science policy-space models in that that it incorporates the role of law. In the case-space model, the way to represent a case is by locating it in a n-dimensional space of of possible cases, the case-space. A case then denotes a legally relevant event that has occurred out of many that could have occurred. Put more simply, a case is a bundle of legally relevant facts. A legal rule then is a cut, a cut point when the case-space is one-dimensional, that divides the case-space. An individual disposition of a case is then the judgment of an individual judge of the case depending on their preference over legal rules (the cut point) and the location of the case in the case-space. In other words, if the case at hand falls to one side of the judge's cut point, then they vote for certain outcome, if it falls on the other side, they vote against it.

@landaDisagreementsCollegialCourts2007 draw from the case-space model multiple theoretical sources of disagreement. The first and clear source of disagreement among judges is that about facts. Different judges may place the facts of the case in the case-space differently. There other sources of disagreement: which dimensions should be relevant under any given legal rule to determine the disposition of a case, disagreement about "thresholds" within dimensions, and a couple of more sources of disagreement, which all can be summarized as a disagreement about the legal rule.

To this end, we simplify the model into two similar characteristics that concern the facts and the legal rule: case complexity and case controversy. Case complexity in our understanding refers to the number of legal issues that a case has touched upon. In line @landaDisagreementsCollegialCourts2007 we suppose that the more legal rules there is in play in any given case, the more room for disagreement about rules. We are also able to distinguish between different types of legal issues. Case controversy refers to the facts. There are subjects matters that we believe are more prone to disagreement.
That said, our work is based on the Wittig model, according to which semi-structured interviews with judges were designed to gain a deeper understanding of the disagreement on a bench and norm-identification from a judge's point of view. But before we get to the methodology we further present results from empirical research on dissents in different countries and build on our paper.

### Research on dissent {#research}

We now present an overview of the conclusions reached by the empirical legal scholarship on dissents. 

In Argentinian Supreme Court dissent are longer and they are more likely to occur in important cases [@muroExploringDissentSupreme2020], which is in line with the conclusion of @epsteinWhyWhenJudges2011 that the majority reacts to the separate opinion with a more extensive reasoning.

Regarding the identity theory, results from Canadian Constitutional Court shows that women dissent more frequently than their male peers, especially when their policy preferences diverge [@johnsonSpeakingWomenDissenting2020] and  the likelihood of dissent is strongly related to four broad factors that appear to exert independent influence on whether the Court is consensual or divided:  political conflict, institutional structure, legal ambiguity in the law and variations in the leadership style of the chief justice [@songerExplainingDissentSupreme2011]. 

European countries have also become a subject of research.  In the context of the Estonian Supreme Court, Hanretty argues that dissenting opinions are not political.  Rather, they relate to differences between the judges about the proper way of evaluating the claims of plaintiffs, with judges on one side preferring to take plaintiffs’ claims of rights infringements as valid on the face of it, and then establish the proportionality of the alleged infringement, and judges on the other side preferring to reject such claims [@hanrettyJudicialDisagreementNeed2015]. In the Spanish Council of State professional background and demographics seems to be the most powerful explanatory variables rather than characteristics of the case [@garoupaJudicialDissentCollegial2022]. Study of the Danish Supreme Court revealed that in the period of January 2014 to April 2015 dissent constituted less than 10 percent of the cases. The primary factor that engendered dissent appeared to be ECHR cases [@bentsenExplainingDissentRates2021]. A comparative study of Slovenia and Croatia showed how political factors, in this case party fractionalization, can also be important predictors of dissent due to specific legal tradition. Surprisingly in this study neither the effect of court workload nor the effect of adjudicating panel size, emphasized by individual rational-choice explanations, exert a statistically significant effect on dissent [@garoupaSpurredLegalTradition2020]. Results from comparative study of Constitutional Courts of Latvia, Germany, Czech Republic, Poland, Slovenia indicate that legal and policy characteristics matter, but so do judicial backgrounds and the issues reviewed [@brickerBreakingPrincipleSecrecy2017]. Therefore, the results and the trends are rather mixed and inconclusive.

From the above mentioned results we can sense that not all of those hypotheses and models are replicable  for different legal contexts. In some CCE countries, information about voting is not public, the process of appointment of judges differs, which  affects the politicization of their decision-making. We have to take into account that European legal judicial tradition differs from the US. Bricker notes that unlike the SCOTUS, which now is almost exclusively comprised of career judges, European constitutional judges arrive to the court from diverse paths: some arrive after careers in the ordinary court system, some arrive with backgrounds in academia, and others arrive after careers in politics [@brickerBreakingPrincipleSecrecy2017]. Also legal professions in civil-law systems have been comparatively much more tightly embedded into a unified state bureaucracy [@garoupaSpurredLegalTradition2020]. 
Qualitative research based on interviews with judges are not uncommon [@brickerBreakingPrincipleSecrecy2017; @domnarskiFederalJudgesRevealed2009; @epsteinChoicesJusticesMake1997; @smekalMimopravniVlivyNa2021] however they are not a typical tool for their decision-making analysis since they can be bound by the law on confidentiality, not willing to participate [@nirApproachingBenchAccessing2018] or a guinea pig effect can occur [@smekalMimopravniVlivyNa2021]. Despite these problems and possible distortions of qualitative research we argue that in some legal cultures, empirical limitations can be further developed on qualitative research. Thus deeper understanding of the institutional context is needed.


## Czech Constitutitonal Court {#primer}

We now introduce the CCC, its institutional and procedural background, its powers as well as its composition. The CCC consists of fifteen judges, out of which one is the president of the CCC, two are vice presidents and twelve associate judges [following the terminology of @kosarConstitutionalCourtCzechia2020]. These fifteen judges are appointed by the president of the Czech republic upon approval of the Senate, the upper chamber of the Czech two-chamber Parliament. The judges enjoy 10 years terms with the possibility of re-election; there is no limit on the times a judge can be re-elected. The three CCC functionaries are unilaterally appointed by the Czech president.

The appointment procedure is similar to how the SCOTUS judges are appointed as the procedure lays in the hands of the president of the republic and the upper chamber. The minimal requirement for a CCC nominee are 40 years of age, a clean criminal record, a finished legal education and experience in the legal field. Other than that, the nomination is left to the consideration of the President of the Republic. After a nomination, the nominee is firstly interviewed in the constitutional law committee of the Senate, which produces an unbinding recommendation for the plenary Senate hearing. The final binding decision is then made by simple majority of the Senate plenary hearing. This procedure has lead to a situation, in which there is very little variance as to the nominating background of the judges. First, there is no nominating political party akin to the US context or the Spanish context [@hanrettyDissentIberiaIdeal2012]. Second, because the court was established in 1993 and filled within roughly a year of its establishment and because the term of the Czech president is 5 years and all the 3 Presidents, who'd finished their term at the time of writing this article, have been elected twice (for ten years it total), each president has had the chance to appoint all the fifteen members of "their" CCC. Therefore, the first term of the CCC has been termed the Václav Havel, the second the Václav Klaus and the third Miloš Zeman terms of the CCC.

Regarding the competences, the CCC is a typical Kelsenian court inspired mainly by the German Federal Constitutional Court. The CCC enjoys the power of abstract constitutional review, including constitutional amendments. The abstract review procedure is initiated by political actors (for example MPs) and usually concerns political issues. Moreover, an ordinary court can initiate a concrete review procedure, if that court reaches the conclusion that a legal norm upon which its decision depends is not compatible with the constitution. Individuals can also lodge constitutional complaints before the CCC. Lastly, the CCC can also resolve separation-of-powers disputes, it can *ex ante* review international treaties, decide on impeachment of the president of the republic, and it has additional ancillary powers [for a complete overview, see @kosarConstitutionalCourtCzechia2020].

The CCC is an example of a collegial court. From the perspective of the inner organization, the CCC can decide in four bodies: (1) individual judges in the role of judge rapporteur, (2) 3-member chambers (*senáty*), (3) the plenum (*plénum*), and (4) special disciplinary chamber. The 3-member chambers and the plenum play a crucial role. The plenum is composed of all judges, whereas the four 3-member chambers are composed of the associate judges. Neither the president of the CCC or her vice-presidents are permanents members of the 3-member chambers. Until 2016, the composition of the chambers was static. However, in 2016, a system of regular 2-yearly rotations was introduced, wherein the president of the chamber rotates to a different every 2 years. I am of the view that such a institutional change opens up potential for quasi-experimental research similar to the @gschwendAreJudgesPolitical2016 study utilizing judge absences within the 3-member chambers of the German federal constitutional court. In general, the plenum is responsible for the abstract review, whereas the 3-member chambers are responsible for the individual constitutional complaints.

In the chamber proceedings, decisions on admissibility must be unanimous, whereas decisions on merits need not be, therefore, a simple majority of two votes is necessary to pass a decision on merits. In the plenum, the general voting quorum is a simple majority and the plenum is quorate when there are ten judges present. The abstract review is one of the exceptions that sets the quorum higher, more specifically to 9 votes.

A judge rapporteur plays a crucial role [@chmelZpravodajoveSenatyVliv2017; @horenovskyProcessMakingConstitutional2015 study the large influence of the judge rapporteurs at the CCC]. Each case of the CCC gets assigned to a judge rapporteur. The assignment is regulated by a case allocation plan. They are tasked with drafting the opinion, about which the body then votes. The president of the CCC (in plenary cases) or the president of the chamber (in chamber cases) may re-assign a case to a different judge rapporteur if the draft opinion by the original judge rapporteur did not receive a majority of votes. Unfortunately, the CCC does not keep track of these reassignments.

The act on the CCC allows for separate opinions. They can take two forms: dissenting or concurring opinions. Each judge has the right to author a separate opinion, which then gets published with the CCC decision. It follows that not every anti-majority vote implies a separate opinion, it is up to the judges to decide whether they want to attach a separate opinion with their vote. Vice-versa, not every separate opinion implies an anti-majority vote, as the judges can attach a concurring opinion. In contrast to dissenting opinion, when a judge attaches a concurring opinion, they voted with the majority but disagree with its argumentation.^[Which makes it difficult to, for example, conduct the same point-estimation with data on dissenting behavior of judges as @hanrettyDissentIberiaIdeal2012 has done on the Portugese and Spanish Constitutional Courts.] Unfortunately, it is difficult to conduct research on the dissent aversion because the voting is kept secret.

Judges can dissent both in chambers or plenary decisions. The Venice Commision report on separate opinions of Constitutional Courts states that:  *„In the Czech Republic, the experience of the communist regime led to the introduction of separate opinions, which were seen as a means of protecting the personal integrity of individual judges. They continue to fulfil this role to this day. It is therefore important for a judge of the Czech Constitutional Court that a clear indication in the heading of each decision is included stating the name of the judge rapporteur who prepared the majority finding….The Czech doctrine claims that judges who draft separate opinions take off their mask of anonymity, because they have openly admitted that they do not agree with the majority and that the Court’s decision was not reached unanimously. It also shows that the winning legal opinion was not accepted unequivocally, but that it was reached after difficult deliberations and after consideration of various arguments. Linking separate opinions to the name of a particular judge increases his or her responsibility for voting and content of the separate opinion.“* [@venicecommissionREPORTSEPARATEOPINIONS2018]

It is important to note that a separate opinion in the 3-member chamber decisions almost at all time reveals that the vote was split. XX % of cases result in inadmissibility, in which an unanimous vote is required. An inadmissibility decision entails only a quasi-meritorious review that results into the conclusion that a case does not contain a question of constitutional law.  A rejection already entails review on merits. It follows that if one of the judges decides to dissent in the 3-member chamber, the decisions has to be made on merits, which further makes it legally more binding and the judge rapporteur is typically forced to change the structure of the decision and make the argumentation more comprehensive. This further disincentivizes separate opinions in the 3-member chamber proceedings as the decision to dissent turns a non-binding decision containing a majority opinion, with which the dissenting justice disagrees, into a binding decision on merits and it imputes large effort costs on the judge rapporteur. 

The room for the dissenting judge and the majority to address each other differs between the two bodies. There is less back and forth interplay between the judges, more akin to the SCOTUS context, and most of the communication is handled remotely in the panel proceedings, whereas the plenum meets regularly to discuss the cases in person. Despite that, procedurally speaking, the process of generating separate opinions is the same. In both cases, the rapporteurs are informed about the outcome of the vote, which is filed in the voting record. The separate opinion is then sent to the judge rapporteur before the decision is announced, as it cannot be added until after the announcement. It is important to note that judges have the possibility, not the obligation, to dissent. In other words, there is room for judges to give way to strategic considerations.

me# Method and Data

To answer our research questions, we conducted semi-structured interviews, “a qualitative data collection strategy in which the researcher asks informants a series of predetermined but open-ended questions” (Given, 2008) with justices of the third decade of the CCC.
We contacted all 15 CCC justices, out of which 9 agreed to participate in the research, 2 refused to participate and the rest did not respond to our repeated requests. The interviewee provided interviews with the condition of subsequent anonymization and approval. To unify anonymity, we present quotes from all interviewees in plural.
A written interview guide with a list of topics to be covered was developed in advance in accordance with the literature review. Once informed consent was obtained from the participants, interviews were conducted by one of the authors in an office of individual judges directly in the building of the CCC located in Brno from July 2023 to August 2023. The interviews took 50 minutes on average.
The interviews were recorded, transcribed verbatim, and analyzed using the ATLAS.ti software kit. Thematic analysis, “a method for identifying, analyzing and reporting patterns (themes) within data” (Braun & Clarke, 2006), was used to organize and describe the dataset. The authors coded the interviews and consolidated codes into several content domains using the inductive approach. 

## Predelat + RQ predelat
The thematic analysis revealed two main themes.  Firstly we will focus on the process of making a dissent: what are the unwritten rules, how rotation of chambers affected the CCC, which cases made an impact and aspects of interaction and communication at CCC. Secondly we present the three types of dissenting judges  and motivation of judges towards disents. There are four subthemes: previous experience, emotional vent, workload and importance of the case.  

# Interviews evalutation
We now separately discuss two main themes that appeared in the interviews. Firstly, in [subsection X](#birth) we delve into the process of how a separate opinion comes about. While there are some formal rules, over time, informal habits and unwritten rules have developed. Secondly, in [subsection Y](#stances) we analyse the various stances that the justices take towards dissent.

## The birth of dissent at CCC {#birth}
Although the procedure at the CCC is governed by the act on the CCC as well as its internal rules of procedure, it is important to map the internal process that takes place before a court's decision explore the potential room that justices have to break away from the majority. We discuss the 3-member chamber and the plenary proceedings somewhat separately. We start with the former. First of all, when a case arrives at CCC a judge rapporteur is randomly assigned. judge rapporteur mostly prepares the draft of the court decision after some familiarization with the file and sends it to their colleagues for further discussion. The judge rapporteur then discusses the case with other justices. The style of communication in chambers depends on prior agreement. Some of the justices prefer to meet in person, while others communicate per e-mail. It could be said that some justices prefer a more personal approach rather than e-mail communication. However, when the case is complicated or something is problematic one of the justices may suggests a meeting in person.

*„E-mail correspondence at the beginning, followed by a phase when the colleagues you have approached are asked to express themselves. So they'll respond electronically again, actually send the text back after editing, and some will ask for in-person meeting. If that doesn't settle the matter, then the three-judge chamber will meet all together.“*^[R6]

Judges present their opinion during the deliberation. It is in this phase that a dissent comes about, if one of the judges decides to break away from the majority opinion. While the judges are coming prepared for the deliberation, it is unlikely that the decision of dissent had already been made prior to it. Furthermore, a separate opinion in the 3-member chamber decisions presents an interesting paradox: as explained one of the interviewees, the costs of a dissent in the chamber proceedings are very high since it forces the judge rapporteur to do more work and since it tranforms the decision into a binding *nález*:

*„If the judge rapporteur proposes a decision on inadmissibility, and I disagree, I will force the judge rapporteur to invite the parties to make a statement, others to reply… I feel obliged to write the dissent for the sake of it and not to let everything wear down the judge rapporteur, who suddenly has a lot more work to do, and so in that case I feel obliged to also spit out some idea and explain to some extent why the ruling is being made by way of a judgment“*^[R1]

It is not only the collegiality cost that judges consider in the chamber proceedings. Strategic considerations also come into play since the dissent can transform from a non-binding decision to binding judgment. A non-binding decision on inadmissibility requires unanimous vote. Therefore, voting against the majority and dissenting turns the non-binding majority opinion into a binding opinion contained in a decision on merits:

*„It's just that in some cases, I've made, and I'll say this as a frankly strategic consideration, that knowing that I would be in the minority, you actually when you do a dissent in the Chamber, you make a denial of a resolution that is not intended to preclude a binding denied finding. So I was making and even in this case I was making and even on the floor a strategic consideration that it was better to be rejected on inadmissibility than to be rejected on merits.“*^[R8]

Interestingly, the strategizing judges also consider with whom they sit on the bench. The rotation of judges at the CCC was introduced in 2016. Since then, once every two years, one member of a chamber “rotates” into another. One of the judges revealed that they strategically wanted to resolve the case with the current composition, as the justice considered those more prominent in the legal community and cared about the academic impact of the case:

*„…so actually by passing the decision in the more difficult chamber and gaining support from my colleagues, had a lot more public legitimacy.“*^[R8]

After signing the voting protocol, the judge rapporteur waits for and collects separate opinions and then announces the case. 

The situation in plenary cases is quite different: plenary sessions are mandatory in person and planned on every Tuesday. If a judge rapporteur wants to discuss their case on plenary meeting, they have to send the draft of the decision, including facts of the case and their proposed outcome, per e-mail a week before the planned plenary session. This is an unwritten rule, which is respected by the judges:

*„There is a sort of friendly rule that if you want your case to be discussed in the plenary meeting on Tuesday, you have to send it by 12:00 on the previous Tuesday and give your colleagues a week. If it's something more complicated it is better to send it up 14 days before the meeting or so… and then of course it's up to the president of the CCC who sets up the plenary.“*^[R5]

After a  judge rapporteur sends their draft, some of the judges may react to the draft by sending their comments and any suggestions to that particular case. At this stage, the potential dissenting groups are already starting to take shape:

*„Usually it's that the judge who has some reservations about it before the plenary session and writes out in advance what his reservations are and sends it out to everybody else becomes the leader of the dissenting group and then most people tend to sort of join in and possibly write something of their own here and that's sort of the way that the group is formed. Whoever starts dissenting.“*^[R1]

One of the judges explained how they perceive "opinion leaders" within these dissenting groups. It is not by any means that the “opinion leaders” are always the same judges. Opinion leaders, as they were described by our respondent, are willing to invest their free time in preparing and commenting on the cases of others:

*„Yeah, just type-wise and personality-wise you're going to have a judge who likes to debate more, who likes to argue, who doesn't resist, who always like goes into that opinion clash and  then you're always going to have a judge who listens to that and then some even maybe join in or be persuaded. Which, of course, within that 15-member body, you have to have both groups of judges because if you have 15 opinion leaders, you're never going to have anything like a decision there. If you have 14 submissive judges who just vote according to the opinion leader, you're going to have a monocratic CCC.“*^[R5]

Some of the judges argue that opinion leaders are selected based on their expertise in certain area of law. For example, in a criminal case, a judge who has previous experience in criminal law will be more forthcoming. Some of our respondents presented themselves as opinion leaders, since they consider it their duty to always speak up when they disagree with the majority opinion. It can happen that the opinion leader will arise during the debate at the plenary meeting. It is not a rule that opinion leaders are only those, who comment on the case in advance. The voting coalitions are also emerging in this point. The judges agree that they can infer from the debate, even before the voting, how other judges will vote since most of the judges present their opinion or at least announce with whom they agree:

[sem bych dal ještě zdroj k některým tvrzením z toho předchozího odstavce]

*„And then my experience is that after voting, when I know that four colleagues vote against the judgment like me, I always offer them: do you want to sign my dissent or not?“*^[R5]

However, there are some exceptions, under which the judges do not speak up and only then quietly announce that they will express themselves in a separate opinion. But that really does happen in exceptional situations.  After the debate, if the chamber president finds that the case has been sufficiently discussed, he will open the vote. The unwritten rule is that judges at this stage will definitely confirm whether they will dissent or not. In the plenary proceedings, the situation is different:

*„In plenary matters, of course, the situation is different and there is an unwritten rule, that a dissenting opinion must be invoked at the latest when the voting record is signed.“*^[R2]

In the case of dissent, it is necessary to give dissenters enough time to write their separate opinion. In practice, judges are usually given a week to write the dissent:

*„Yes, and again, we don't have any rules of procedure, but [....], the decision is generally published at the same time as the dissent, so that there is a practice of about one week between the adoption of the decision and its publication, including the preparation and publication of the middle opinion.“*^[R2]

[Co je middle opinion?]

After the vote, it is decided when the case will be announced. The dissenters have time until then to file a dissent. A curious case occurred in the case of the repeal of the law on elections to the Chamber of Deputies Pl. US 44/17. This case was mentioned by all of our nine intervenes in this context. The problem that arose was that the case was  held by the judge rapporteur for three-years before issuing a final decision. After the vote however, the chairman of CCC decided that the case will be announced the next day, since it repealed part of the law eight months before the elections to the Chamber of Deputies. The dissenting judges criticized in the dissent the lack of time given which then lead to new agreement between judges that a week should be guaranteed at minimum for writing a dissent.  A judge rapporteur may lose their case. In that scenario, the chairman put the case forward to the „most convincing opinion leader” (who got the most votes) that becomes judge rapporteur. In this case, the judge rapporteur uses their draft as a basis for dissent.

*„It may be that those comments will convince the majority of the plenary to change the decision and also the rapporteur-judge, and therefore you will very likely be the new rapporteur, because the President will assume that you are prepared for this, since you presented all the arguments. You've probably already thought this through like you've been working on it.“*^[R5]

To sum up, we identify these types of judges during the coalition making of a decision: an original judge rapporteur, opinion leaders(s), president of the CCC (who presides over a session of the court) and the remaining judges who join in the opinion of either judge rapporteur, or one of the opinion leader or they express their own opinion, which no one joins. After the vote, the opinion leaders become dissent leaders or in case of a change of judge rapporteur the opinion leader becomes the new judge rapporteur, while the old judge rapporteur becomes the dissenting leader. After the vote, dissent leader(s) ask  other colleagues  whether they want to join. Most of the judges perceive joint dissent as an advantage. 

[Vyrok o tom, ze to pripojeni se vnimaji soudci jako vyhodu.]

However even here we can spot some exceptions.

*Researcher: …. and has it ever happened to you that maybe a judge wanted to have a solitary dissent and didn't want to invite you?*
*Interviewee: Yeah as far as I recall there was a situation like that with one of the judges.*

After deciding who will write with whom the dissent, the judges get down to writing. The judges perceive greater literary freedom in the possibility of a solitary dissent, which aligns with the finding of @clarkLocatingSupremeCourt2010 that separate opinions align the most with the political position of SCOTUS judges. Joint dissents are most often written by the dissent leader. The other judges in the dissenting coalition mainly comment on it or make suggestions. In a few cases, there has also been joint writing of dissents (each writing a specific portion).

[Tady chybí opět nějaký úryvek z rozhovorů]

## The fan, hater and strategist {#stances}

In the interviews, we were able to identify three overarching types of attitude towards dissent among judges: the fan, the hater and the strategist. The main difference between these three groups lies in their norm-identification, or their internal attitude on how the court should act externally. Haters of dissent argue that the CCC should not outwardly appear disunited by any dissents and instead should try to appear as united and unanimous as possible. These judges adhere to the norm of consensus to full extent. It is possible to find dissents even from the haters. They differ in the degree of disagreement required for them to dissent: simply put a hater needs a much greater degree of disagreement on a bench to exercise dissent, whereas the threshold of the fans is lower, since a disunited court externally is not perceived as a major problem - on the contrary, they perceives the plurality of opinions positively. Strategists are somewhere in the middle of both these views. They are neither completely open to dissent nor completely closed to it, simply put, they dissent where it strategically suits them. We now present an example for each type and then delve deeper into the understanding of each type.

An example of a hater: *„I don't like them (dissents). […] I believe that when a decision is taken by a majority, it is not to comment further on some B that someone thought otherwise.“*^[R3]
An example of a fan: *„I'm a big fan of dissent […] And I can safely say that so far, I've been on the CCC for many years now, I've dissented every time I've voted no. It's a sign of fairness to explain even outwardly why I didn't support the majority opinion here.“*^[R5]
An example of a strategist: *„I think that dissent makes sense if one expresses a fundamental position or a fundamental opinion. I am motivated by a different legal opinion or the hope that it may lead to a change in either case law or legislation in the future.“*^[R1]

Indeed we are aware that these three types are a simplified model that does not explain all the variance in the dissenting behavior at the CCC. Even the judges from the group of those who don't like dissent, dissent in some cases. There is not a single judge without a dissent at CCC. Therefore, we need to delve deeper. One of the  factors is the previous profession of constitutional judge. When the CCC judge is coming from the ordinary court system, they are not used to dissent unless they were a judge at the Supreme Court or Supreme Administrative Court for only the SAC allows for dissents under specific and narrow circumstances, otherwise judges in Czechia are not legally allowed to attach separate opinions. For a career judge one of the main aspects of judicial decision-making is to create legal certainty for the public. A dissenting opinion, from their point of view, undermines this certainty.

*„Basically, from my point of view, it undermines the authority of the court to some extent. It was simply decided by majority vote, period.“*

So how is it possible that even these judges sometimes dissent? In one response, two factors played a large role for the decision to overcome their aversion towards dissenting: 1) a high level of disagreement and 2) the possibility to join the dissent of another judge who shares similar view. One of the judges explained to us:

*„Whether it's a value… so yeah I made an agreement with a colleague who felt the need to write the dissent. I would read it to consider whether or not to join.“*^[R]

Furthermore judges who like to dissent and dissent as much as possible have different reasons why they do so. They manage to dissent every time that they vote against the majority opinion. However, that does not imply that they are always the authors of the dissents, since it would be nearly impossible due to time management and the amount of workload at the CCC. It's almost as if the option to explain their differing view is perceived as an obligation:

Interviewee: *„it may not be a legal obligation, but I feel it's my professional obligation to write a dissent; from a legal standpoint is a judge's possibility  not a duty, but I feel it's an ethical duty for a judge to always write a dissent if they vote no.“*
Interviewee: *„it should simply be the principle that the judge should reveal why he was against.“*

There are four main aspects that further explain the decision of CCC judges whether to dissent: 1) previous experience, 2) emotional valve, 3) caseload and 4) importance of the case. Previous experience, caseload, as well as the importance of the case flow from our theory and we have already tested them empirically [@paulikDisagreementBenchEmpirical2024], on the other hand, the need to release emotions has not been thematized in the literature on dissent.

[OVERIT] 

### Previous experience

The CCC as an apex court represents for a share of Czech lawyers the pinnacle of their careers. The President of the Czech Republic nominates candidates for CCC judges and the Senate approves them. As a rule, the president should nominate as diverse a constitutional court as possible - they seek diversity not only in terms of gender but also in terms of profession. The CCC judges have in the past encompassed academics, lawyers, but also judges of higher and lower courts. The professional background of CCC judges shapes their stance and views towards the role and functioning of the CCC and it also influences the familiarity among CCC judges - some have already met at a district court or at a department at university, some of them don't know each other. That opens up an interesting dynamic that develops over time as the newly appointed justices have to get accustomed to their new position as well as to their new colleagues:

*„Often those social relationships come from some previous work - I don't know, I know some of my colleagues from the university department.“*^[R5]

One interviewee revealed that judges perceive the previous profession of their colleagues and at the same time transfer their knowledge from the former profession to the current one.

Interviewee: *„Then an academic comes along at CCC and they are used to writing academic papers and that's a bit different than writing judgments or dissent. In an academic paper you're completely free, you can just write whatever you want and you're the only signed under it and it actually influences the academic discussion, but it doesn't directly affect people's fates.“*^[R3]
Interviewee: *„Many colleagues see the judgment as some kind of scientific work. For me, as a common judge, it's a judgment... the basis of judicial work is to respect the majority ruling. If the majority outvotes me, I obey and secondly, it is equally basic to judicial work to respect the binding legal opinion of a higher authority.“*^[R4]
Interviewee: *„Obviously, for example, if somebody is not a judge and now they're actually judging here for the first time, it's a bit of a problem for them to learn the procedures at court.“*^[R3]

There are three additional sub-themes that surfaced during our interviews and that we believe deserve further inquiry that is beyond the scope of our paper. First, it appears that judges from lower courts are less likely to dissent since they are used to the binding nature of the decision of an appellate court and at the same time they are more aware of the aspect of undermining the authority of the court by dissent. Since this is very difficult to verify quantitatively in the Czech context, because the number of judges from non-supreme courts is minimal, the in-depth interviews suggest that that may indeed be the case:

*„Because I was a routine judge I believe that if a decision was made by a majority, no one should further comment further on some other solutions or that he thought otherwise.“*^[R4]

Secondly, it appears that the judges who come from the Supreme Court and Supreme Administrative Court perceive this aspect differently as they come from a court at the top of the hierarchy, at which separte opinions are allowed under narrow circumstances. Moreover, judges at higher court have the power to determine what direction the case law should take, while lower court judges must learn to obey the higher courts. That situation was described by one of our respondents as follows: 

*„If you're asking about the judicial career, it's related to the fact that as you grow to the higher levels, then of course you're more interested in influencing that jurisprudence by your rulings.“*^[R3]

Lastly, it appears that judges with background in the academia and without experience as a judge have the ambition to take on an academic dimension in the decision/judgment. At the same time, one can also expect more freedom in the writing of dissents:

*„Academics have it differently. They're able to sort of overlook the verdict and have the ambition to sort of show like in the judicial opinion or in the dissents, express ideas beyond the court's decision.“*^[R4]

### Emotional vent
Every Interviewee touched upon the topic of emotions and frustration resulting from a plenary or chamber discussion. A portion of the CCC judges admitted that frustration sometimes leads them to writing a separate opinion. Dealing with emotions has proven to be an important aspect of their stance towards dissents. In a fundamental disagreement, a judge does not need to bottle up their emotions but they can just vent them out through dissent.

Researcher: "*So if I may start - what is the meaning of a written dissent for you?*
Interviewee: *„It's kind of a relief, if we don't agree that we do, in the reasoning or something else - it's a safety valve to agree at all.“*^[R6]

[Tady ten překlad tý interviewee odpovědi je weird]

The CCC judges agreed that a highly emotioanlly charged dissent is more readily and easily written alone than together with others because a solitary dissent does not have to be approved by anyone else: 

*„Honestly when you write it yourself you are making less compromises.“*^[R5] 

Some judges revealed that they do not experience the need to vent emotions. Interestingly, those who do not experience such frustrations reminisced about their previous judicial careers:

*„I'd have to hang myself if I was that emotional in the justice system. Of course, when I was young and stupid, the court of appeal dismissed some of my cases. So I read it and wrote it like they wanted from me, period.“*^[Chybi resp. v orginalnim dokumentu]

Interesting research questions emerge out of the interviews: To what extent is the dissenting behavior influenced by the perceived role of dissents as an avenue for venting emotions? What factors influence the variance of the role of emotions venting through a dissent? To our knowledge, such a question has not been thoroughly empirically researched and opens up an interesting research avenue. Does it depend on the previous professional experience as some interviewees seem to hint? We present a couple of fragments that enlighten this aspect of a dissent. It follows from the interviews that motions may lead to strong personal expressions in dissent. Most held the view that dissent should not interfere on a personal level and argued that that would be strictly unethical and unprofessional:

Researcher: *„You said that it can improve the relationships in that court, and often there are dissents that seem to me to attack the judge rapporteur rather than the“* [tady neco chybi]

Interviewee: *„I'll stop you there, that's an ethically total mistake. You don't write dissent at all by saying what they did was wrong. Dissent to me is always offering a different way of dealing with it. I mean, I've never, I don't think any dissent of mine has ever been as impolite, because I've actually just offered an alternative solution. And even I've avoided that sort of "my colleagues are a disappointment to me" and so on and so on, maybe at some point like that, but it's certainly not what I was primarily writing, but just that maybe I was joining someone.“*^[R8]

But some defended opposite approach with the following argument:

*„Someone said that simply the dissent is lost. Yeah I just failed to get a majority for my arguments, but when there is a loss it should be as fair. So I recognize that if it's not fair, there's an opportunity to argue back on a more personal level.“*^[R9]

Those judges simply feel that a procedural injustice was done against them; that the only way to  draw attention to this problem is to write a dissent that is intended to inform the public of some injustice that has taken place in the Constitutional Court. Therefore, a less calculated, less strategic dimension of the emotional plane emerges.

### Workload
The importance of leisure and workload was already discussed in the [section X](#research). The question remains how is the role of workload perceived by individual judges at CCC? The haters of dissent are more likely to spend time on their cases rather than writing dissent. In contrast to that, the fans of dissent are more likely to ignore their workload. The strategists weight and decide whether they can afford to dissent regarding the amount of caseload he is dealing with at the moment.

A hater: *„Well, I don't have time to write dissents and stuff like that (laughs).“*^[R4]
A fan: *„I dissent every time.“*
A strategist: *„If I'm against it but it's not worth a dissent, either because I don't consider it so fundamental, or that or just for completely prosaic reasons that I just don't have the time.“*^[R9]

We therefore reveal that the typically researched effect of workload may vary across certain clusters of judges. To our knowledge this heterogeneity of the effect has not been studied at all. Our interviews therefore open another potential research avenue.

Furthermore, we revealed a collegiality effect regarding caseload. The CCC judges take into account whether their dissent imputes extra work on the judge rapporteur. Extra work can be a situation, in which the judge rapporteur is forced to rewrite an inadmissibility decision to a judgment as the law requires the admissibility decisions to be unanimous. Another situation occurs when a dissent causes delays in the proceedings. The dissenting judge tries as much as possible to convince the judge-reporter of their view, which ultimately delays the entire process of the decision-making and subsequent announcement of the judgment. Such time delays, which can lead to an increase in the workload of both judges, lead the dissenting judge to exercise dissent as their reputiation among their colleagues could suffer.

[Tu to chce jeste citat]

The collegiality and effort costs also come into play in joint separate opinions. Some judges admitted to having been agreed in advance to take turns writing dissents when voting together or they simply ask each other to write the separate opinion for time reasons. Long-term joint dissenting collaborations arise from frequent forms of voting and consensus [@vartazaryanSitOvaAnalyza2022; @paulikDisagreementBenchEmpirical2024].

*„We decided who would write the dissent and then we communicated among ourselves and sent it to the other judges. We took the comments into account, so like then it was a collective work, but like every text, somebody just has to write the basis.“*^[R5]

### Importance of the case
There is not a single judge of CCC with zero separate opinions. Tab. X reveals the dissent rate for each of the CCC judges of its third term. [DODELAT]
It appears that the importance of a case is another key aspects behind the decision whether to dissent. Fance should according to their strategy dissent in every case in which they vote against the majority. The factor of importance is rather very subjective, since the boundaries of importance of the individual case are partly dependent on the judges and their perception. There is not a definition that unites the undecided judges. Their views on which case is important differ

*„I think dissent is a fairly strong expression of disagreement, and often one disagrees over less substantive things. I think that dissent is meaningful if one is expressing a fundamental position or a fundamental opinion.“*^[R1]
*„It is really just supposed to be a question of legal opinion, strong legal opinion, not some kind of impressionology that I think something and it is a big question whether to bring into it the way of, for example, making that decision.“*^[R7]
*„Really depends on the particular case. I distinguish the dissenters by how I see them, of course. There may be someone else may say it's just different it's not that important. I judge it by what I think of it and if I then pay more attention to it, but that doesn't mean I don't pay less attention to those at it as important. Of course it's how they handle it. Because just like the decision you have it the same that yeah I address that decision as more important so I give it more attention.“*^[R3]

[u toho tretiho citatu je divny to "at it as important"]

Despite the impossibility of discerning a pattern from the interviews that would reveal what judges consider as an important case, one insight is often repeated. That is that plenary cases are more influential in terms of social impact. As already mentioned, the CCC may repeal part of a law or even the entire law in a plenary decision. While in the 3-member chamber cases the CCC decides on individual constitutional complaints.

*„When it's some principled matter of value especially in plenary cases. In the Senate decision I never dissent. Whether it's about plenary or some core constitutional values, yeah I agreed with a colleague who felt the need to write the dissent that I would read it to consider whether or not to join in.“*^[R4]
*„The plenary cases have a much greater significance and reach."*^[R2]


# Conclusion

